//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Name,Type,Style,C/P,Expiry,Strike price,CCY
        ///123,CDE LTD,StockOption,European,C,01.04.2017,100,USD
        ///124,ABC INC,StockOption,European,C,01.04.2017,20,PLN
        ///125,CDE LTD,StockOption,European,P,01.04.2017,120,USD
        ///126,CDE LTD,StockOption,European,P,01.04.2017,140,USD
        ///127,CDE LTD,StockOption,European,C,01.07.2016,100,USD
        ///128,ABC INC,StockOption,European,P,01.07.2016,50,PLN
        ///129,CDE LTD,StockOption,European,C,01.10.2016,100,USD
        ///130,ABC INC,StockOption,European,P,01.10.2016,50,PLN.
        /// </summary>
        internal static string CsvPrice {
            get {
                return ResourceManager.GetString("CsvPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,CCY pair,Type,Style,C/P,Expiry,Strike rate,Notional amount,CCY
        ///234,USDPLN,FXOption,European,C,01.04.2017,4.0000,100000,USD
        ///235,USDPLN,FXOption,European,C,01.04.2017,4.0200,100000,PLN
        ///236,USDPLN,FXOption,European,P,01.04.2017,4.1000,90000,USD
        ///237,USDPLN,FXOption,European,P,01.04.2017,4.0300,12000,USD
        ///238,USDPLN,FXOption,European,C,01.07.2016,4.1000,11000,USD
        ///239,USDPLN,FXOption,European,P,01.07.2016,4.0300,100000,PLN
        ///240,USDPLN,FXOption,European,C,01.10.2016,4.0200,100000,USD
        ///241,USDPLN,FXOption,E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FX {
            get {
                return ResourceManager.GetString("FX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,CCY pair,Type,Style,C/P,Expiry,Strike rate,Notional amount,CCY
        ///234,USDPLN,FXOption,European,C,01.04.2017,4.0000,100000,USD
        ///235,USDPLN,FXOption,European,C,01.04.2017,4.0200,100000,PLN
        ///236,USDPLN,FXOption,European,P,01.04.2017,4.1000,90000,USD
        ///237,USDPLN,FXOption,European,P,01.04.2017,4.0300,12000,USD
        ///238,USDPLN,FXOption,European,C,01.07.2016,4.1000,11000,USD
        ///239,USDPLN,FXOption,European,P,01.07.2016,4.0300,100000,PLN
        ///240,USDPLN,FXOption,European,C,01.10.2016,4.0200,100000,USD
        ///241,USDPLN,FXOption,E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FxOptions {
            get {
                return ResourceManager.GetString("FxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;portfolio&gt;
        ///&lt;trade id=&quot;123&quot; name=&quot;CDE LTD&quot; type=&quot;StockOption&quot; style=&quot;European&quot; cp=&quot;C&quot; expiry=&quot;2017-04-01&quot; strike=&quot;100&quot; ccy=&quot;USD&quot; /&gt;
        ///&lt;trade id=&quot;124&quot; name=&quot;ABC INC&quot; type=&quot;StockOption&quot; style=&quot;European&quot; cp=&quot;C&quot; expiry=&quot;2017-04-01&quot; strike=&quot;20&quot; ccy=&quot;PLN&quot; /&gt;
        ///&lt;trade id=&quot;125&quot; name=&quot;CDE LTD&quot; type=&quot;StockOption&quot; style=&quot;European&quot; cp=&quot;P&quot; expiry=&quot;2017-04-01&quot; strike=&quot;120&quot; ccy=&quot;USD&quot; /&gt;
        ///&lt;trade id=&quot;126&quot; name=&quot;CDE LTD&quot; type=&quot;StockOption&quot; style=&quot;European&quot; cp=&quot;P&quot; expiry=&quot;2017-04-01&quot; st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlPrice {
            get {
                return ResourceManager.GetString("XmlPrice", resourceCulture);
            }
        }
    }
}
